#.travis.yml

language: node_js

sudo: required

dist: trusty

node_js:
  - 10.6

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - set -e
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build --prod --base-href /

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_failure: change
    on_success: change
